name: "Code-Style Fixer"

on:
    push:
        branches: [ main ]

jobs:
    fix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v3

            -   name: Checking PHP Syntax
                uses: TheDragonCode/php-codestyler@v1.8.7
                with:
                    fix: true
