name: phpunit
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "8.0" ]
                psql: [ "9-alpine", "10-alpine", "11-alpine", "12-alpine", "13-alpine", "14-alpine" ]

        name: php ${{ matrix.php }}, l ${{ matrix.laravel }}, pg ${{ matrix.psql }}

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: default
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

            postgres:
                image: postgres:${{ matrix.psql }}
                ports:
                    - 5432:5432
                env:
                    POSTGRES_DB: default
                    POSTGRES_USER: root
                    POSTGRES_PASSWORD: root

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, gd, redis, pdo_mysql, pdo_pgsql
                    coverage: none

            -   name: Install dependencies
                run: composer require --dev laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
                env:
                    MYSQL_HOST: 127.0.0.1
                    PGSQL_HOST: 127.0.0.1
