name: phpunit
on: [ push ]

env:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_HOST: 127.0.0.1

jobs:
    build:
        runs-on: ubuntu-20.04

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "8.0" ]

        name: Laravel ${{ matrix.laravel }}, PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_mysql, pdo_pgsql, iconv, bcmath
                    coverage: none

            -   name: Shutdown MySQL
                run: sudo service mysql stop

            -   name: Setup MySQL
                uses: mirromutth/mysql-action@v1
                with:
                    mysql version: 'latest'
                    character set server: 'utf8mb4'
                    collation server: 'utf8mb4_unicode_ci'
                    mysql root password: $MYSQL_ROOT_PASSWORD

            -   name: Wait for MySQL
                run: |
                    while ! mysqladmin ping --host=$MYSQL_HOST --password=$MYSQL_ROOT_PASSWORD --silent; do
                      sleep 1
                    done

            -   name: Setup PostgreSQL
                uses: huaxk/postgis-action@v1
                with:
                    postgresql password: $MYSQL_ROOT_PASSWORD
                    postgresql user: root

            -   name: Install dependencies
                run: |
                    composer require laravel/framework:^${{ matrix.laravel }}
                    composer update --prefer-stable --prefer-dist --no-progress --no-interaction

            -   name: Execute tests
                run: sudo vendor/bin/phpunit
